// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: post.proto

package vyletdatabase

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Alt           *string                `protobuf:"bytes,2,opt,name=alt,proto3,oneof" json:"alt,omitempty"`
	Width         *int64                 `protobuf:"varint,3,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *int64                 `protobuf:"varint,4,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Image) GetAlt() string {
	if x != nil && x.Alt != nil {
		return *x.Alt
	}
	return ""
}

func (x *Image) GetWidth() int64 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Image) GetHeight() int64 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Image) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Image) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	AuthorDid     string                 `protobuf:"bytes,3,opt,name=author_did,json=authorDid,proto3" json:"author_did,omitempty"`
	Images        []*Image               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Caption       *string                `protobuf:"bytes,5,opt,name=caption,proto3,oneof" json:"caption,omitempty"`
	Facets        []byte                 `protobuf:"bytes,6,opt,name=facets,proto3,oneof" json:"facets,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Post) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Post) GetAuthorDid() string {
	if x != nil {
		return x.AuthorDid
	}
	return ""
}

func (x *Post) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *Post) GetFacets() []byte {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostRequest) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePostRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePostResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uris          []string               `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostsRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

type GetPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Posts         map[string]*Post       `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse) Reset() {
	*x = GetPostsResponse{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse) ProtoMessage() {}

func (x *GetPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse.ProtoReflect.Descriptor instead.
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetPostsResponse) GetPosts() map[string]*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetPostsByActorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByActorRequest) Reset() {
	*x = GetPostsByActorRequest{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByActorRequest) ProtoMessage() {}

func (x *GetPostsByActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByActorRequest.ProtoReflect.Descriptor instead.
func (*GetPostsByActorRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostsByActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *GetPostsByActorRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPostsByActorRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetPostsByActorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Posts         map[string]*Post       `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByActorResponse) Reset() {
	*x = GetPostsByActorResponse{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByActorResponse) ProtoMessage() {}

func (x *GetPostsByActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByActorResponse.ProtoReflect.Descriptor instead.
func (*GetPostsByActorResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *GetPostsByActorResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetPostsByActorResponse) GetPosts() map[string]*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetPostsByActorResponse) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type GetPostInteractionCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostInteractionCountsRequest) Reset() {
	*x = GetPostInteractionCountsRequest{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostInteractionCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostInteractionCountsRequest) ProtoMessage() {}

func (x *GetPostInteractionCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostInteractionCountsRequest.ProtoReflect.Descriptor instead.
func (*GetPostInteractionCountsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostInteractionCountsRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type PostInteractionCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         int64                  `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Replies       int64                  `protobuf:"varint,2,opt,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInteractionCounts) Reset() {
	*x = PostInteractionCounts{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInteractionCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInteractionCounts) ProtoMessage() {}

func (x *PostInteractionCounts) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInteractionCounts.ProtoReflect.Descriptor instead.
func (*PostInteractionCounts) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *PostInteractionCounts) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostInteractionCounts) GetReplies() int64 {
	if x != nil {
		return x.Replies
	}
	return 0
}

type GetPostInteractionCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Counts        *PostInteractionCounts `protobuf:"bytes,2,opt,name=counts,proto3,oneof" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostInteractionCountsResponse) Reset() {
	*x = GetPostInteractionCountsResponse{}
	mi := &file_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostInteractionCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostInteractionCountsResponse) ProtoMessage() {}

func (x *GetPostInteractionCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostInteractionCountsResponse.ProtoReflect.Descriptor instead.
func (*GetPostInteractionCountsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{12}
}

func (x *GetPostInteractionCountsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetPostInteractionCountsResponse) GetCounts() *PostInteractionCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

type GetPostsInteractionCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uris          []string               `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsInteractionCountsRequest) Reset() {
	*x = GetPostsInteractionCountsRequest{}
	mi := &file_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsInteractionCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsInteractionCountsRequest) ProtoMessage() {}

func (x *GetPostsInteractionCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsInteractionCountsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsInteractionCountsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{13}
}

func (x *GetPostsInteractionCountsRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

type GetPostsInteractionCountsResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Error         *string                           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Counts        map[string]*PostInteractionCounts `protobuf:"bytes,2,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsInteractionCountsResponse) Reset() {
	*x = GetPostsInteractionCountsResponse{}
	mi := &file_post_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsInteractionCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsInteractionCountsResponse) ProtoMessage() {}

func (x *GetPostsInteractionCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsInteractionCountsResponse.ProtoReflect.Descriptor instead.
func (*GetPostsInteractionCountsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{14}
}

func (x *GetPostsInteractionCountsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetPostsInteractionCountsResponse) GetCounts() map[string]*PostInteractionCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\rvyletdatabase\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x05Image\x12\x18\n" +
	"\x03cid\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\x12\x15\n" +
	"\x03alt\x18\x02 \x01(\tH\x00R\x03alt\x88\x01\x01\x12\x19\n" +
	"\x05width\x18\x03 \x01(\x03H\x01R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x04 \x01(\x03H\x02R\x06height\x88\x01\x01\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mimeB\x06\n" +
	"\x04_altB\b\n" +
	"\x06_widthB\t\n" +
	"\a_height\"\xd8\x02\n" +
	"\x04Post\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\x12\x18\n" +
	"\x03cid\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid\x12%\n" +
	"\n" +
	"author_did\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tauthorDid\x12,\n" +
	"\x06images\x18\x04 \x03(\v2\x14.vyletdatabase.ImageR\x06images\x12\x1d\n" +
	"\acaption\x18\x05 \x01(\tH\x00R\acaption\x88\x01\x01\x12\x1b\n" +
	"\x06facets\x18\x06 \x01(\fH\x01R\x06facets\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"indexed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAtB\n" +
	"\n" +
	"\b_captionB\t\n" +
	"\a_facets\"<\n" +
	"\x11CreatePostRequest\x12'\n" +
	"\x04post\x18\x01 \x01(\v2\x13.vyletdatabase.PostR\x04post\"9\n" +
	"\x12CreatePostResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"-\n" +
	"\x11DeletePostRequest\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\"9\n" +
	"\x12DeletePostResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"-\n" +
	"\x0fGetPostsRequest\x12\x1a\n" +
	"\x04uris\x18\x01 \x03(\tB\x06\xbaH\x03\xc8\x01\x01R\x04uris\"\xc8\x01\n" +
	"\x10GetPostsResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12@\n" +
	"\x05posts\x18\x02 \x03(\v2*.vyletdatabase.GetPostsResponse.PostsEntryR\x05posts\x1aM\n" +
	"\n" +
	"PostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vyletdatabase.PostR\x05value:\x028\x01B\b\n" +
	"\x06_error\"x\n" +
	"\x16GetPostsByActorRequest\x12\x18\n" +
	"\x03did\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03did\x12\x1c\n" +
	"\x05limit\x18\x02 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\xfe\x01\n" +
	"\x17GetPostsByActorResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12G\n" +
	"\x05posts\x18\x02 \x03(\v21.vyletdatabase.GetPostsByActorResponse.PostsEntryR\x05posts\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x01R\x06cursor\x88\x01\x01\x1aM\n" +
	"\n" +
	"PostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.vyletdatabase.PostR\x05value:\x028\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_cursor\";\n" +
	"\x1fGetPostInteractionCountsRequest\x12\x18\n" +
	"\x03uri\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03uri\"W\n" +
	"\x15PostInteractionCounts\x12\x1c\n" +
	"\x05likes\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x05likes\x12 \n" +
	"\areplies\x18\x02 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\areplies\"\x95\x01\n" +
	" GetPostInteractionCountsResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12A\n" +
	"\x06counts\x18\x02 \x01(\v2$.vyletdatabase.PostInteractionCountsH\x01R\x06counts\x88\x01\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_counts\">\n" +
	" GetPostsInteractionCountsRequest\x12\x1a\n" +
	"\x04uris\x18\x01 \x03(\tB\x06\xbaH\x03\xc8\x01\x01R\x04uris\"\xff\x01\n" +
	"!GetPostsInteractionCountsResponse\x12\x19\n" +
	"\x05error\x18\x01 \x01(\tH\x00R\x05error\x88\x01\x01\x12T\n" +
	"\x06counts\x18\x02 \x03(\v2<.vyletdatabase.GetPostsInteractionCountsResponse.CountsEntryR\x06counts\x1a_\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.vyletdatabase.PostInteractionCountsR\x05value:\x028\x01B\b\n" +
	"\x06_error2\xdf\x04\n" +
	"\vPostService\x12Q\n" +
	"\n" +
	"CreatePost\x12 .vyletdatabase.CreatePostRequest\x1a!.vyletdatabase.CreatePostResponse\x12Q\n" +
	"\n" +
	"DeletePost\x12 .vyletdatabase.DeletePostRequest\x1a!.vyletdatabase.DeletePostResponse\x12K\n" +
	"\bGetPosts\x12\x1e.vyletdatabase.GetPostsRequest\x1a\x1f.vyletdatabase.GetPostsResponse\x12`\n" +
	"\x0fGetPostsByActor\x12%.vyletdatabase.GetPostsByActorRequest\x1a&.vyletdatabase.GetPostsByActorResponse\x12{\n" +
	"\x18GetPostInteractionCounts\x12..vyletdatabase.GetPostInteractionCountsRequest\x1a/.vyletdatabase.GetPostInteractionCountsResponse\x12~\n" +
	"\x19GetPostsInteractionCounts\x12/.vyletdatabase.GetPostsInteractionCountsRequest\x1a0.vyletdatabase.GetPostsInteractionCountsResponseB\x84\x01\n" +
	"\x11com.vyletdatabaseB\tPostProtoP\x01Z\x10./;vyletdatabase\xa2\x02\x03VXX\xaa\x02\rVyletdatabase\xca\x02\rVyletdatabase\xe2\x02\x19Vyletdatabase\\GPBMetadata\xea\x02\rVyletdatabaseb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_post_proto_goTypes = []any{
	(*Image)(nil),                             // 0: vyletdatabase.Image
	(*Post)(nil),                              // 1: vyletdatabase.Post
	(*CreatePostRequest)(nil),                 // 2: vyletdatabase.CreatePostRequest
	(*CreatePostResponse)(nil),                // 3: vyletdatabase.CreatePostResponse
	(*DeletePostRequest)(nil),                 // 4: vyletdatabase.DeletePostRequest
	(*DeletePostResponse)(nil),                // 5: vyletdatabase.DeletePostResponse
	(*GetPostsRequest)(nil),                   // 6: vyletdatabase.GetPostsRequest
	(*GetPostsResponse)(nil),                  // 7: vyletdatabase.GetPostsResponse
	(*GetPostsByActorRequest)(nil),            // 8: vyletdatabase.GetPostsByActorRequest
	(*GetPostsByActorResponse)(nil),           // 9: vyletdatabase.GetPostsByActorResponse
	(*GetPostInteractionCountsRequest)(nil),   // 10: vyletdatabase.GetPostInteractionCountsRequest
	(*PostInteractionCounts)(nil),             // 11: vyletdatabase.PostInteractionCounts
	(*GetPostInteractionCountsResponse)(nil),  // 12: vyletdatabase.GetPostInteractionCountsResponse
	(*GetPostsInteractionCountsRequest)(nil),  // 13: vyletdatabase.GetPostsInteractionCountsRequest
	(*GetPostsInteractionCountsResponse)(nil), // 14: vyletdatabase.GetPostsInteractionCountsResponse
	nil,                           // 15: vyletdatabase.GetPostsResponse.PostsEntry
	nil,                           // 16: vyletdatabase.GetPostsByActorResponse.PostsEntry
	nil,                           // 17: vyletdatabase.GetPostsInteractionCountsResponse.CountsEntry
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_post_proto_depIdxs = []int32{
	0,  // 0: vyletdatabase.Post.images:type_name -> vyletdatabase.Image
	18, // 1: vyletdatabase.Post.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: vyletdatabase.Post.indexed_at:type_name -> google.protobuf.Timestamp
	1,  // 3: vyletdatabase.CreatePostRequest.post:type_name -> vyletdatabase.Post
	15, // 4: vyletdatabase.GetPostsResponse.posts:type_name -> vyletdatabase.GetPostsResponse.PostsEntry
	16, // 5: vyletdatabase.GetPostsByActorResponse.posts:type_name -> vyletdatabase.GetPostsByActorResponse.PostsEntry
	11, // 6: vyletdatabase.GetPostInteractionCountsResponse.counts:type_name -> vyletdatabase.PostInteractionCounts
	17, // 7: vyletdatabase.GetPostsInteractionCountsResponse.counts:type_name -> vyletdatabase.GetPostsInteractionCountsResponse.CountsEntry
	1,  // 8: vyletdatabase.GetPostsResponse.PostsEntry.value:type_name -> vyletdatabase.Post
	1,  // 9: vyletdatabase.GetPostsByActorResponse.PostsEntry.value:type_name -> vyletdatabase.Post
	11, // 10: vyletdatabase.GetPostsInteractionCountsResponse.CountsEntry.value:type_name -> vyletdatabase.PostInteractionCounts
	2,  // 11: vyletdatabase.PostService.CreatePost:input_type -> vyletdatabase.CreatePostRequest
	4,  // 12: vyletdatabase.PostService.DeletePost:input_type -> vyletdatabase.DeletePostRequest
	6,  // 13: vyletdatabase.PostService.GetPosts:input_type -> vyletdatabase.GetPostsRequest
	8,  // 14: vyletdatabase.PostService.GetPostsByActor:input_type -> vyletdatabase.GetPostsByActorRequest
	10, // 15: vyletdatabase.PostService.GetPostInteractionCounts:input_type -> vyletdatabase.GetPostInteractionCountsRequest
	13, // 16: vyletdatabase.PostService.GetPostsInteractionCounts:input_type -> vyletdatabase.GetPostsInteractionCountsRequest
	3,  // 17: vyletdatabase.PostService.CreatePost:output_type -> vyletdatabase.CreatePostResponse
	5,  // 18: vyletdatabase.PostService.DeletePost:output_type -> vyletdatabase.DeletePostResponse
	7,  // 19: vyletdatabase.PostService.GetPosts:output_type -> vyletdatabase.GetPostsResponse
	9,  // 20: vyletdatabase.PostService.GetPostsByActor:output_type -> vyletdatabase.GetPostsByActorResponse
	12, // 21: vyletdatabase.PostService.GetPostInteractionCounts:output_type -> vyletdatabase.GetPostInteractionCountsResponse
	14, // 22: vyletdatabase.PostService.GetPostsInteractionCounts:output_type -> vyletdatabase.GetPostsInteractionCountsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	file_post_proto_msgTypes[0].OneofWrappers = []any{}
	file_post_proto_msgTypes[1].OneofWrappers = []any{}
	file_post_proto_msgTypes[3].OneofWrappers = []any{}
	file_post_proto_msgTypes[5].OneofWrappers = []any{}
	file_post_proto_msgTypes[7].OneofWrappers = []any{}
	file_post_proto_msgTypes[8].OneofWrappers = []any{}
	file_post_proto_msgTypes[9].OneofWrappers = []any{}
	file_post_proto_msgTypes[12].OneofWrappers = []any{}
	file_post_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
